INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393', 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333', 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222', 'CR');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333', 'EC');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO, PAIS_NACIMIENTO) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555', 'EC');

INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('22222', 'AHORRO', 1, true);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('33333', 'CORRIENTE', 1, false);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('22222', 'AHORRO', 1, true);
INSERT INTO CUENTA (NUMERO, TIPO, CLIENTE_ID, ESTADO) VALUES ('33333', 'CORRIENTE', 1, false);
